name: boardli
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.4
  go_router: ^17.1.0
  responsive_sizer: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
  
  fonts: 
  - family: e-Ukraine
    fonts: 
      - asset: assets/fonts/e-Ukraine-UltraLight.otf
        weight: 100
      - asset: assets/fonts/e-Ukraine-Thin.otf
        weight: 200
      - asset: assets/fonts/e-Ukraine-Light.otf
        weight: 300
      - asset: assets/fonts/e-Ukraine-Regular.otf
        weight: 400
      - asset: assets/fonts/e-Ukraine-Medium.otf
        weight: 500
      - asset: assets/fonts/e-Ukraine-Bold.otf
        weight: 700
        